### get all tickets
GET https://ticketing.dev/api/tickets
Accept: application/json


### create
POST https://ticketing.dev/api/tickets
Content-Type: application/json

{
  "title": "TEST TITLE",
  "price": 100
}


### update ticket
PUT https://ticketing.dev/api/tickets/64e52f2be4b8ca588db34296
Content-Type: application/json

{
  "title": "Hello this is mememe",
  "price": "0.3"
}


### get single ticket
GET https://ticketing.dev/api/tickets/64d8e9532b0767b3c2d1618f
Accept: application/json
