apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: ticketing/payments
          name: payments
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: STRIPE_KEY_TEST
              valueFrom:
                secretKeyRef:
                  name: stripe-key-test
                  key: STRIPE_KEY_TEST
            - name: MONGO_URI
              value: mongodb://payments-mongo-svc:27017/payments
            - name: NATS_URL
              value: http://nats-svc:4222
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payments-svc
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      targetPort: 3000 # this is the one that the container exposes, in other words the one we run the app at from the container.
      port: 3000 # this is the one that the service exposes