### get all tickets
GET https://ticketing.dev/api/orders
Accept: application/json


### create
POST https://ticketing.dev/api/orders
Content-Type: application/json

{
  "ticketId": "64e93c04ee77b82fa361271c"
}

