### get all tickets
GET https://ticketing.dev/api/orders
Accept: application/json


### create
POST https://ticketing.dev/api/orders
Content-Type: application/json

{
  "ticketId": "64e40432b7a4580f0ca5ba43"
}


### update ticket
PUT https://ticketing.dev/api/tickets/64e25576b6513fb17cf8d163
Content-Type: application/json

{
  "title": "Hello this is me",
  "price": "0.1"
}


### get single ticket
GET https://ticketing.dev/api/tickets/64d8e9532b0767b3c2d1618f
Accept: application/json
